---
# For our purposes it is sufficient to use fewer resources. Using default values can lead to lack of resources.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-vpp-node
  namespace: calico-vpp-dataplane
spec:
  template:
    spec:
      containers:
        - name: agent
          image: docker.io/calicovpp/agent:v3.23.0
          resources:
            requests:
              cpu: 150m
        - name: vpp
          image: docker.io/calicovpp/vpp:v3.23.0
          resources:
            requests:
              cpu: 250m
