---
version: 1.0
root: "./.results"
timeout: 600
shuffle-enabled: true
statistics:
  enabled: true
  interval: 30

providers:
  - name: "kind-1"
    kind: "shell"
    instances: 1
    node-count: 3
    retry: 1
    enabled: true
    timeout: 300
    env:
      - KIND_CLUSTER_NAME=cloudtest-kind-$(rands10)
    scripts:
      start: |
        kind create cluster --name ${KIND_CLUSTER_NAME} --config cluster-config.yaml --wait 120s
      config: |
        sh -c "kind get kubeconfig --name ${KIND_CLUSTER_NAME} > \"${KIND_CLUSTER_NAME}-kubeconfig\" && echo \"${KIND_CLUSTER_NAME}-kubeconfig\""
      stop: |
        kind delete cluster --name ${KIND_CLUSTER_NAME}
  - name: "kind-2"
    kind: "shell"
    instances: 1
    node-count: 3
    retry: 1
    enabled: true
    timeout: 300
    env:
      - KIND_CLUSTER_NAME=cloudtest-kind-$(rands10)
    scripts:
      start: |
        kind create cluster --name ${KIND_CLUSTER_NAME} --config cluster-config.yaml --wait 120s
      config: |
        sh -c "kind get kubeconfig --name ${KIND_CLUSTER_NAME} > \"${KIND_CLUSTER_NAME}-kubeconfig\" && echo \"${KIND_CLUSTER_NAME}-kubeconfig\""
      stop: |
        kind delete cluster --name ${KIND_CLUSTER_NAME}
reporting:
  junit-report: "./.results/junit.xml"
executions:
  - name: "Sample go tests"
    env:
      - MY_ENV_VAR="test"
    root: .
    source:
      tags:
        - interdomain
    timeout: 60
    cluster-count: 2
    cluster-selector:
      - kind-1
      - kind-2
    cluster-env:
      - KUBECONFIG_CLUSTER_1
      - KUBECONFIG_CLUSTER_2
