// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "context"
	_ "github.com/antonfisher/nested-logrus-formatter"
	_ "github.com/kelseyhightower/envconfig"
	_ "github.com/networkservicemesh/api/pkg/api/registry"
	_ "github.com/networkservicemesh/sdk/pkg/tools/debug"
	_ "github.com/networkservicemesh/sdk/pkg/tools/log"
	_ "github.com/networkservicemesh/sdk/pkg/tools/signalctx"
	_ "github.com/sirupsen/logrus"
	_ "github.com/spiffe/go-spiffe/v2/spiffetls/tlsconfig"
	_ "github.com/spiffe/go-spiffe/v2/workloadapi"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/credentials"
	_ "net/url"
	_ "os"
)
