---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prefetch
data:
 prefetch.sh: |
    #!/bin/sh

    for image in ghcr.io/networkservicemesh/ci/cmd-admission-webhook-k8s:33072e8 ghcr.io/networkservicemesh/ci/cmd-forwarder-ovs-use-host-ovs:811ba56 ghcr.io/networkservicemesh/ci/cmd-forwarder-ovs:811ba56 ghcr.io/networkservicemesh/ci/cmd-forwarder-vpp:0f11313 ghcr.io/networkservicemesh/ci/cmd-nsc:3ec1a4d docker.io/frolvlad/alpine-bash:latest ghcr.io/networkservicemesh/ci/cmd-nsc-vpp:4257baa ghcr.io/networkservicemesh/ci/cmd-nse-firewall-vpp:b4cf5bd ghcr.io/networkservicemesh/ci/cmd-nse-icmp-responder:55fad10 ghcr.io/networkservicemesh/ci/cmd-nse-icmp-responder-vpp:240dfce ghcr.io/networkservicemesh/ci/cmd-nse-supplier-k8s:9c4b8c9 ghcr.io/networkservicemesh/ci/cmd-nsmgr:d9c0b2c ghcr.io/networkservicemesh/ci/cmd-nsmgr-proxy:6368aec ghcr.io/networkservicemesh/ci/cmd-map-ip-k8s:5332918 ghcr.io/networkservicemesh/ci/cmd-registry-k8s:fb3788f ghcr.io/networkservicemesh/ci/cmd-registry-memory:f63cca1 ghcr.io/networkservicemesh/ci/cmd-registry-proxy-dns:d13b54a gcr.io/spiffe-io/wait-for-it:latest gcr.io/spiffe-io/spire-agent:1.0.2 gcr.io/spiffe-io/spire-server:1.0.2 gcr.io/spiffe-io/k8s-workload-registrar:1.0.2; do
      if ! ctr -n=k8s.io image ls -q | grep "${image}"; then
        ctr -n=k8s.io image pull "${image}"
      fi
    done
